[workspace]
name = "genesis-world"
# Standard Conda channel for Python and system tools
channels = ["conda-forge"]
# Supports Windows, Linux, Apple Silicon Mac
platforms = ["win-64", "linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
build = "python build.py --target=local"

[system-requirements]
# Required for modern Linux wheels (like pymeshlab)
libc = { family = "glibc", version = "2.35" }

[dependencies]
# Downgrade to 3.12.* if you get compatibility errors
python = "3.13.*"

[pypi-dependencies]
# Editable project install
genesis-world = { path = ".", editable = true }

# --- Feature: CUDA (GPU) ---
[feature.cuda.pypi-options]
# Switch url to cu128 or cu126 for better driver compatibility
extra-index-urls = ["https://download.pytorch.org/whl/cu130"]
# "unsafe-best-match": Correctly mixes CUDA wheels (from URL) with standard packages (from PyPI)
index-strategy = "unsafe-best-match"

[feature.cuda.pypi-dependencies]
torch = "*"
torchvision = "*"

# --- Feature: CPU-Only ---
[feature.cpu.pypi-dependencies]
# Uses standard PyPI (CPU on Linux/Mac, or default CUDA 12.x on Windows)
torch = "*"
torchvision = "*"

[feature.agf-server.pypi-dependencies]
websockets = "*"
pint = "*"

# --- Feature: Build Tools ---
[feature.build.dependencies]
nuitka = ">=2.4"
pyinstaller = "*"
# Using standard pixi channels for tools
[feature.build.target.linux-64.dependencies]
patchelf = "*"
ccache = "*"

[feature.build.target.win-64.dependencies]


[environments]
default = ["cuda", "agf-server", "build"]
cpu-only = ["cpu", "agf-server", "build"]
